cREAL | Test deploy configurator contract on alfajores
moolamarket/moola-v2 pull request #10
Opened 2022-01-07 20:23 UTC by x-moola

- contract:
contracts/TTConfigurator.sol

- Replaced the asset to a new ERC20 token test token`0xf72f494d34ed668085525fd87ceb9248cb882590`

- deploy command:
`npm run external:deploy-TT-configurator-alfajores`

- Sample deployed contracts:
Network: alfajores
tx: 0xf1826cbb1cf15e0896f89b04be57d8ec7e84e38f8b138ee9899bc55ee20772d7
Test Token (TT) address: 0xf72f494d34ed668085525fd87ceb9248cb882590
contract address: 0x91e2aDF155eB43A860D4384de4a2660eA92CC4fF
deployer address: 0xAc4B966e4e01662DccA10f96a05415d31efCB761
gas price: 510000000
gas used: 1394694

2022-01-12 17:06 UTC, x-moola commented on helpers/constants.ts
> +  CREAL: oneEther.multipliedBy('0.040204').toFixed(),
Here I'm not sure what number should be used for CREAL 🤔

2022-01-13 09:41 UTC, lastperson requested changes

2022-01-13 09:41 UTC, lastperson commented on contracts/protocol/lendingpool/cREAL/CREALConfiguratorAlfajores.sol
> +contract CREALConfigurator is Ownable {
```suggestion
contract CREALConfiguratorAlfajores is Ownable {
```

2022-01-13 09:41 UTC, lastperson commented on contracts/protocol/lendingpool/cREAL/CREALConfiguratorCelo.sol
> +contract CREALConfigurator is Ownable {
```suggestion
contract CREALConfiguratorCelo is Ownable {
```

2022-01-13 09:42 UTC, merged