add contracts to repay from collateral
moolamarket/moola-v2 pull request #13
Opened 2022-01-24 05:13 UTC by alexandr-martirosyan

2022-01-25 16:23 UTC, ytumanov approved these changes

2022-01-25 17:16 UTC, lastperson requested changes

2022-01-26 15:30 UTC, lastperson commented on cli.js
> +  console.info('repay-from-collateral address collateralAsset(celo|cusd|ceur) debtAsset(celo|cusd|ceur) debtRateMode(1|2) debtRepayAmount useFlashloan(true|false) [privateKey]');
also need to add creal.

2022-01-27 12:01 UTC, lastperson commented on cli.js
> +      console.log('Approve UniswapAdapter', (await mToken.methods .approve(repayAdapter.options.address, maxCollateralAmount) .send({ from: user, gas: 2000000 })).transactionHash);
formatting broke.

2022-01-27 12:05 UTC, lastperson commented on cli.js
> +    console.error('invalid number');
Would be helpful to print which number is wrong (print num as well).

2022-01-27 12:06 UTC, lastperson commented on cli.js
> +function isValidAsset(asset) {
lets move this one inside execute(), and use `if (!tokens[asset]) ...`, otherwise we'll need to maintain multiple places with assets.

2022-01-28 10:01 UTC, merged