Add RepaymentHelper contract
moolamarket/moola-v2 pull request #23
Opened 2022-03-02 07:27 UTC by x-moola

Add RepaymentHelper contract that:
repays debt on behalf of another account, if the specified amount is more than the actual debt, deposits the remaining amount to the delegatee. 

Deployed on Alfajores:
[0xFac3C2B3D81903e71796d6388218cc2d93a7a7AB](https://alfajores-blockscout.celo-testnet.org/address/0xFac3C2B3D81903e71796d6388218cc2d93a7a7AB/transactions)

## TODO
- [ ] Testing and verify

2022-03-18 07:54 UTC, lastperson commented
Contract is good, just need to add tests and deploy.

2022-03-28 15:39 UTC, x-moola commented
Tests will be added in a separate PR

2022-03-28 17:06 UTC, lastperson requested changes

2022-03-28 17:06 UTC, lastperson commented on cli.js
> +      (await token.methods.approve(lendingPool.options.address, amount).send({ from: user, d }))
something seem to be broken with 'd' ?

2022-03-28 17:06 UTC, lastperson commented on cli.js
> +      pk = process.env.CELO_BOT_PK || params[5];
```suggestion
      pk = params[5];
```

2022-03-28 17:06 UTC, lastperson commented on cli.js
> +      const repayDelegationCallTx = await repayDelegationHelper.methods
should check/give approvals before calling repay.

2022-03-29 08:13 UTC, lastperson commented on cli.js
> +      if (currentAllowance < amount) {
those value are either string or big numbers, in both cases lessThan operator wouldn't work as expected.

2022-03-29 17:31 UTC, merged